"""Writes src/codicons.generated.ts: the outlines of the codicons a change's
card draws its actions with, so the card shows the icon the same action has
in VS Code's menus (a-change-is-acted-on-from-its-card, ADR 0044).

Run out of band, like the Metro icon subset (vendor/metro-icons/README.md):
the outlines are read from the codicon font a VS Code installation ships,
and nothing is downloaded. Codicons are (c) Microsoft, licensed CC BY 4.0;
the generated file says so.

    python packages/webui/scripts/extract-codicons.py "<VS Code>/resources/app"

Needs fontTools (`pip install fonttools`). The names are those of
packages/core/src/change-actions.ts; codicons.test.ts fails while one is
missing here.
"""

import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

NAMES = [
    "play", "comment", "debug-stop", "checklist", "diff", "history", "type-hierarchy-super",
    "credit-card", "graph", "info", "lightbulb", "folder-opened", "files", "gear", "link",
    "debug-disconnect", "archive", "debug-reverse-continue", "trash",
]


def main() -> None:
    app = Path(sys.argv[1])
    font = TTFont(app / "out" / "media" / "codicon.ttf")
    glyphs = font.getGlyphSet()
    size = font["head"].unitsPerEm
    lines = [
        "// Generated by scripts/extract-codicons.py from the codicon font VS Code",
        "// ships. Do not edit. Codicons (c) Microsoft, licensed CC BY 4.0:",
        "// https://github.com/microsoft/vscode-codicons",
        "",
        "/** The outlines' square: a path is drawn in a viewBox of this size, y down. */",
        f"export const CODICON_SIZE = {size};",
        "",
        "/** Each codicon's outline, as an SVG path. */",
        "export const CODICON_PATHS: Readonly<Record<string, string>> = {",
    ]
    for name in NAMES:
        if name not in glyphs:
            raise SystemExit(f"{name}: no such glyph in the font")
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(pen)
        # Font units are y up; flip them once here, so the page draws as is.
        flipped = flip(pen.getCommands(), size)
        lines.append(f'  "{name}": "{flipped}",')
    lines += ["};", ""]
    out = Path(__file__).resolve().parent.parent / "src" / "codicons.generated.ts"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {out}")


def flip(commands: str, size: int) -> str:
    """Turns a y-up path into a y-down one: every y becomes size - y."""
    out: list[str] = []
    token = ""
    numbers: list[str] = []
    command = ""

    def flush() -> None:
        if not command:
            return
        values = [float(n) for n in numbers]
        if command in "MLCQ":
            for i in range(1, len(values), 2):
                values[i] = size - values[i]
        elif command == "V":
            values = [size - v for v in values]
        out.append(command + " ".join(fmt(v) for v in values))

    for ch in commands:
        if ch.isalpha():
            if token:
                numbers.append(token)
                token = ""
            flush()
            command = ch
            numbers = []
        elif ch in " ,":
            if token:
                numbers.append(token)
                token = ""
        elif ch == "-" and token and token[-1] != "e":
            numbers.append(token)
            token = ch
        else:
            token += ch
    if token:
        numbers.append(token)
    flush()
    return "".join(out)


def fmt(value: float) -> str:
    rounded = round(value, 2)
    return str(int(rounded)) if rounded == int(rounded) else str(rounded)


if __name__ == "__main__":
    main()
