import type { CatalogTemplate } from "../template-catalog.js";

// Seed built-in template proving the catalog mechanism end to end (see
// openspec/changes/template-catalog/proposal.md). Deliberately narrow —
// well-established, version-stable SQLAlchemy/Alembic setup steps, not a
// claimed curated library.

export const pythonSqlalchemyAlembic: Omit<CatalogTemplate, "origin"> = {
  manifest: {
    id: "python-sqlalchemy-alembic",
    title: "Add SQLAlchemy models + Alembic migrations",
    category: "data-layer",
    version: "1.0.0",
    summary:
      "Adds a SQLAlchemy declarative Base, engine/session setup, and Alembic migration scaffolding to a Python backend that has neither yet.",
    variables: [
      {
        name: "packageName",
        prompt: "Python package/module name for the application (e.g. app)",
        default: "app",
      },
      {
        name: "databaseUrlEnvVar",
        prompt: "Environment variable name holding the database URL",
        default: "DATABASE_URL",
      },
    ],
  },
  artifacts: {
    proposal: `## Why

<!-- Fill in: what forces this change now — a specific feature that needs
persistence, or a specific pain point with the current storage approach. -->

## What Changes

- Add a SQLAlchemy declarative \`Base\`, engine, and session factory to
  \`{{packageName}}/db.py\`, reading the connection string from
  \`{{databaseUrlEnvVar}}\`.
- Add Alembic migration scaffolding (\`alembic.ini\`, \`migrations/\`) wired
  to the same \`Base.metadata\`.
- Add the first migration revision.

## Capabilities

### New Capabilities

- \`data-layer\`: <fill in what this actually covers in your project>

### Modified Capabilities

(fill in if this touches an existing capability's persistence behavior)

## Impact

- New: \`{{packageName}}/db.py\`, \`alembic.ini\`, \`migrations/env.py\`,
  \`migrations/versions/<first-revision>.py\`.
- Dependencies: \`sqlalchemy\`, \`alembic\` (and a driver — e.g.
  \`psycopg[binary]\` for PostgreSQL).
`,
    design: `## Context

<!-- Fill in: current persistence approach (if any), constraints (existing
data to migrate, hosting environment, etc.). -->

## Goals / Non-Goals

**Goals:**
- A single, importable \`Base\`/\`engine\`/session factory other modules can
  depend on.
- Migrations are the only way schema changes reach a real database —
  no implicit \`Base.metadata.create_all()\` in application startup.

**Non-Goals:**
- Not choosing an ORM query style (Core vs ORM session) beyond what this
  change's own models need — that is a project-wide decision to make
  separately if it does not already exist.

## Decisions

### Session lifecycle: <fill in — e.g. one session per request, dependency-injected>

<!-- Rejected alternatives and why. -->

### Migration workflow: <fill in — e.g. autogenerate + manual review before commit>

<!-- Rejected alternatives and why. -->

## Risks / Trade-offs

- **[Risk]** Autogenerated migrations can miss changes Alembic cannot
  detect (column type narrowing, some renames). → **Mitigation**: review
  every autogenerated revision before applying it; do not blindly trust
  \`alembic revision --autogenerate\`.
`,
    tasks: `## 1. SQLAlchemy setup

- [ ] 1.1 Add \`{{packageName}}/db.py\`: declarative \`Base\`, \`engine\` built
  from \`os.environ["{{databaseUrlEnvVar}}"]\`, and a session factory.
- [ ] 1.2 Add the first model(s) using \`Base\`.

## 2. Alembic setup

- [ ] 2.1 \`alembic init migrations\` (or equivalent) and point
  \`migrations/env.py\`'s \`target_metadata\` at \`Base.metadata\` from
  \`{{packageName}}/db.py\`.
- [ ] 2.2 Configure \`alembic.ini\`'s \`sqlalchemy.url\` to read from
  \`{{databaseUrlEnvVar}}\` (not a hardcoded connection string).
- [ ] 2.3 Generate and review the first revision
  (\`alembic revision --autogenerate -m "initial schema"\`).
- [ ] 2.4 Apply it against a real database and confirm the resulting
  schema matches the models (\`alembic upgrade head\`).

## 3. Verification

- [ ] 3.1 Add a test that imports \`{{packageName}}/db.py\` and confirms the
  engine/session factory construct without error given a valid
  \`{{databaseUrlEnvVar}}\`.
`,
  },
};
