// Unified execution protocol: commands and the event stream.
//
// The single place where these types are defined (see
// docs/adr/0001-shared-core-two-delivery-targets.md, item 3). Consumers
// (`server`, `extension`) serialize these same values for their own
// transport (REST/WS, message bridge) and must not define their own variants.

import { STAGES, type HarnessStage } from "./harness-stage.js";
import type { HarnessEffort, HarnessStepBudget } from "./harness-step-agent.js";

export type CommandKind =
  | "plan"
  | "implement"
  | "review"
  | "verify"
  | "status"
  | "list"
  | "show"
  | "validate"
  | "cancel"
  /** Runs `propose → review → apply → verify → archive` in sequence under
   * one `runId`, per `HarnessChainRunner`. Unlike every other command
   * kind, a chain's `runId` is not guaranteed exactly one `"started"`
   * event — a client that counts `"started"` events per `runId` will see
   * one per stage. */
  | "chain"
  | "confirmCheckpoint";

/** Runtime enumeration of `CommandKind`, kept in this one place so
 * transport-boundary shape checks (e.g. `packages/server/src/wire.ts`'s
 * `isCommandLike`) never hand-maintain their own separate copy. */
export const COMMAND_KINDS: readonly CommandKind[] = [
  "plan",
  "implement",
  "review",
  "verify",
  "status",
  "list",
  "show",
  "validate",
  "cancel",
  "chain",
  "confirmCheckpoint",
];

/** One file changed by the run a `"verify"` command is reviewing, carried
 * alongside `CommandContext` so `HarnessChainRunner` can hand a `verify`
 * stage's `Command` the delta of the `apply` run that preceded it (see
 * `security.ts`'s `AgentPromptContextOptions.verifiedDelta`, which is
 * where this actually reaches the agent's prompt). `kind` reuses
 * `CheckpointDelta`'s vocabulary (checkpoint.ts) rather than inventing a
 * second one; `before`/`after` are the file's text content, not a diff. */
export interface VerifiedDeltaEntry {
  path: string;
  kind: "added" | "modified" | "deleted";
  before?: string;
  after?: string;
}

export interface CommandContext {
  /** Absolute path to the OpenSpec change this command applies to. */
  changeDir: string;
  /** Arbitrary data from the change (proposal/design/tasks), passed to the
   * agent as prompt content. This is DATA — see security.ts prepareAgentContext:
   * nothing here can affect the allowlist/cwd/command selection. */
  promptContext?: string;
  /** Files changed by the run being verified, for a `"verify"` command
   * only. Absent for every other command kind, and absent for a `verify`
   * run whose preceding delta could not be determined — see security.ts,
   * "An oversized delta is truncated with a marker, never silently
   * dropped" for what happens once this reaches the prompt. */
  verifiedDelta?: VerifiedDeltaEntry[];
}

export interface Command {
  kind: CommandKind;
  /** Working directory the agent must be run in. */
  cwd: string;
  context: CommandContext;
  /** Run identifier, generated by the caller to correlate events with the
   * request (needed for cancel). */
  runId: string;
  /** Which registered agent (`AgentAdapter.name`/`AgentDescriptor.id`
   * from agents/registry.ts) should execute the command. Optional — the
   * host may use the single configured default agent if the UI layer does
   * not expose agent selection. */
  agentId?: string;
  /** Model to pass to the agent's CLI, resolved from a `stepAgents`
   * entry's object form (see harness-config.ts's `normalizeStepAgent`).
   * Only meaningful for an agent whose registry descriptor declares a
   * `modelFlag`; ignored otherwise. */
  model?: string;
  /** Reasoning effort to pass to the agent's CLI, resolved the same way
   * as `model`. Only meaningful for an agent whose
   * `HARNESS_AGENT_CAPABILITIES` entry declares accepted `effort`
   * values — see harness-step-agent.ts. */
  effort?: HarnessEffort;
  /** Spending cap to pass to the agent's CLI, in that agent's own unit —
   * see harness-step-agent.ts's `HarnessStepBudget`. Only meaningful for
   * an agent whose `HARNESS_AGENT_CAPABILITIES` entry declares a
   * `budgetField`. */
  budget?: HarnessStepBudget;
}

export type EventKind =
  | "started"
  | "stdout"
  | "stderr"
  | "progress"
  | "completed"
  | "failed"
  | "cancelled"
  | "stageCompleted"
  | "checkpoint"
  | "handedOff";

interface BaseEvent {
  runId: string;
  /** ISO 8601 timestamp. */
  timestamp: string;
}

export interface StartedEvent extends BaseEvent {
  kind: "started";
  command: CommandKind;
  cwd: string;
}

export interface StdoutEvent extends BaseEvent {
  kind: "stdout";
  chunk: string;
}

export interface StderrEvent extends BaseEvent {
  kind: "stderr";
  chunk: string;
}

export interface ProgressEvent extends BaseEvent {
  kind: "progress";
  /** Arbitrary human-readable progress message (not necessarily numeric —
   * specific agents report progress differently). */
  message: string;
}

export interface CompletedEvent extends BaseEvent {
  kind: "completed";
  /** Resulting diff/changes, if applicable (best-effort, may be empty). */
  summary?: string;
}

export interface FailedEvent extends BaseEvent {
  kind: "failed";
  reason: string;
}

export interface CancelledEvent extends BaseEvent {
  kind: "cancelled";
}

/** A chain stage finished and the next one is starting immediately (no
 * confirmation required for this transition). */
export interface StageCompletedEvent extends BaseEvent {
  kind: "stageCompleted";
  stage: HarnessStage;
  nextStage: HarnessStage;
}

/** A chain paused between stages, waiting for a `"confirmCheckpoint"` (or
 * `"cancel"`) command before it proceeds to `nextStage`. */
export interface CheckpointEvent extends BaseEvent {
  kind: "checkpoint";
  stage: HarnessStage;
  nextStage: HarnessStage;
  nextAgentId: string;
}

/** A stage was handed to the host's own chat instead of being spawned
 * and observed — see docs/adr/0016-harness-stage-dispatch-via-vscode-
 * chat.md. Non-terminal: nothing observes the chat session's work, so no
 * `completed`/`failed`/`cancelled` follows it for that stage. */
export interface HandedOffEvent extends BaseEvent {
  kind: "handedOff";
  stage: HarnessStage;
}

export type Event =
  | StartedEvent
  | StdoutEvent
  | StderrEvent
  | ProgressEvent
  | CompletedEvent
  | FailedEvent
  | CancelledEvent
  | StageCompletedEvent
  | CheckpointEvent
  | HandedOffEvent;

/** Type guard helper: serializing an Event is just JSON, but we verify
 * that `kind` is one of the known variants when deserializing from an
 * external transport (REST/WS/message bridge), where data arrives as
 * `unknown`. */
export function isEvent(value: unknown): value is Event {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  if (typeof v.runId !== "string" || typeof v.timestamp !== "string") return false;
  switch (v.kind) {
    case "started":
      return typeof v.command === "string" && typeof v.cwd === "string";
    case "stdout":
    case "stderr":
      return typeof v.chunk === "string";
    case "progress":
      return typeof v.message === "string";
    case "completed":
      return v.summary === undefined || typeof v.summary === "string";
    case "failed":
      return typeof v.reason === "string";
    case "cancelled":
      return true;
    case "stageCompleted":
      return (
        typeof v.stage === "string" &&
        STAGES.includes(v.stage as HarnessStage) &&
        typeof v.nextStage === "string" &&
        STAGES.includes(v.nextStage as HarnessStage)
      );
    case "checkpoint":
      return (
        typeof v.stage === "string" &&
        STAGES.includes(v.stage as HarnessStage) &&
        typeof v.nextStage === "string" &&
        STAGES.includes(v.nextStage as HarnessStage) &&
        typeof v.nextAgentId === "string"
      );
    case "handedOff":
      return typeof v.stage === "string" && STAGES.includes(v.stage as HarnessStage);
    default:
      return false;
  }
}

export function serializeEvent(event: Event): string {
  return JSON.stringify(event);
}

export function deserializeEvent(raw: string): Event {
  const parsed: unknown = JSON.parse(raw);
  if (!isEvent(parsed)) {
    throw new Error(`Failed to deserialize Event: unknown format (${raw})`);
  }
  return parsed;
}
