// Unified execution protocol: commands and the event stream.
//
// The single place where these types are defined (see
// docs/adr/0001-shared-core-two-delivery-targets.md, item 3). Consumers
// (`server`, `extension`) serialize these same values for their own
// transport (REST/WS, message bridge) and must not define their own variants.

import { STAGES, isChainPart, type ChainPart, type HarnessStage } from "./harness-stage.js";
import type { AgentUsage } from "./agent-usage.js";
import type { FailureDiagnosis } from "./failure-diagnosis.js";
import type { HarnessEffort, HarnessStepBudget } from "./harness-step-agent.js";

export type CommandKind =
  | "plan"
  | "implement"
  | "review"
  | "verify"
  /** Revises a change's existing planning artifacts from its last review
   * and the operator's notes: the product's `opsx:update` (ADR 0041). */
  | "update"
  | "status"
  | "list"
  | "show"
  | "validate"
  | "cancel"
  /** Runs `propose → review → apply → verify → archive → git` in sequence under
   * one `runId`, per `HarnessChainRunner`. Unlike every other command
   * kind, a chain's `runId` is not guaranteed exactly one `"started"`
   * event — a client that counts `"started"` events per `runId` will see
   * one per stage. */
  | "chain"
  | "confirmCheckpoint"
  /** Answers a `permissionRequest` event by id with an `"allow"`/`"deny"`
   * outcome — see `permissionRequestId`/`permissionOutcome` below and
   * `acp-session-driver.ts`'s `resolvePermission`. Only meaningful for a
   * run started against an ACP-flavored adapter that actually emitted a
   * `permissionRequest`; a target that never emitted one treats it as a
   * no-op (see acp-agent-adapters spec.md's "Permission request
   * answered" scenario). */
  | "resolvePermission"
  /** Asks a run to stop where its work is sound — at a checkpoint at once,
   * inside a stage at the next task boundary — rather than killing it as
   * `cancel` does. Answered by a `stopRequested` event, and carries the
   * reason a person gave in `reason` (a-change-is-run-from-its-card,
   * ADR 0028). */
  | "stop"
  /** Answers a question an agent put to the operator, by its id, with
   * `answer`; written to the change's `decisions.md`, where a run waiting
   * on it reads it (the-agent-asks-the-operator, ADR 0042). */
  | "answerQuestion";

/** Runtime enumeration of `CommandKind`, kept in this one place so
 * transport-boundary shape checks (e.g. `packages/server/src/wire.ts`'s
 * `isCommandLike`) never hand-maintain their own separate copy. */
export const COMMAND_KINDS: readonly CommandKind[] = [
  "plan",
  "implement",
  "review",
  "update",
  "verify",
  "status",
  "list",
  "show",
  "validate",
  "cancel",
  "chain",
  "confirmCheckpoint",
  "resolvePermission",
  "stop",
  "answerQuestion",
];

/** One file changed by the run a `"verify"` command is reviewing, carried
 * alongside `CommandContext` so `HarnessChainRunner` can hand a `verify`
 * stage's `Command` the delta of the `apply` run that preceded it (see
 * `security.ts`'s `AgentPromptContextOptions.verifiedDelta`, which is
 * where this actually reaches the agent's prompt). `kind` reuses
 * `CheckpointDelta`'s vocabulary (checkpoint.ts) rather than inventing a
 * second one; `before`/`after` are the file's text content, not a diff. */
export interface VerifiedDeltaEntry {
  path: string;
  kind: "added" | "modified" | "deleted";
  before?: string;
  after?: string;
}

export interface CommandContext {
  /** Absolute path to the OpenSpec change this command applies to. */
  changeDir: string;
  /** Arbitrary data from the change (proposal/design/tasks), passed to the
   * agent as prompt content. This is DATA — see security.ts prepareAgentContext:
   * nothing here can affect the allowlist/cwd/command selection. */
  promptContext?: string;
  /** Files changed by the run being verified, for a `"verify"` command
   * only. Absent for every other command kind, and absent for a `verify`
   * run whose preceding delta could not be determined — see security.ts,
   * "An oversized delta is truncated with a marker, never silently
   * dropped" for what happens once this reaches the prompt. */
  verifiedDelta?: VerifiedDeltaEntry[];
  /** What the operator wrote when starting an `update`, for its prompt's
   * "The operator's notes" section. Data, like `promptContext`; read only
   * for an `update` (ADR 0041). */
  notes?: string;
  /** The operator's answers to the questions an earlier pass of this run
   * asked, for the pass that goes on with them: the prompt's "The
   * operator's answers" section (ADR 0042). Data, like `notes`. */
  answers?: Array<{ question: string; answer: string }>;
}

export interface Command {
  kind: CommandKind;
  /** Working directory the agent must be run in. */
  cwd: string;
  context: CommandContext;
  /** Run identifier, generated by the caller to correlate events with the
   * request (needed for cancel). */
  runId: string;
  /** Which registered agent (`AgentAdapter.name`/`AgentDescriptor.id`
   * from agents/registry.ts) should execute the command. Optional — the
   * host may use the single configured default agent if the UI layer does
   * not expose agent selection. */
  agentId?: string;
  /** Model to pass to the agent's CLI, resolved from a `stepAgents`
   * entry's object form (see harness-config.ts's `normalizeStepAgent`).
   * Only meaningful for an agent whose registry descriptor declares a
   * `modelFlag`; ignored otherwise. */
  model?: string;
  /** A custom agent to pass to the agent's CLI — a named preset the
   * person defined themselves, resolved from a `stepAgents` entry the
   * same way `model` is. Only meaningful for an agent whose registry
   * descriptor declares a `customAgentFlag`; ignored otherwise. */
  customAgent?: string;
  /** Reasoning effort to pass to the agent's CLI, resolved the same way
   * as `model`. Only meaningful for an agent whose
   * `HARNESS_AGENT_CAPABILITIES` entry declares accepted `effort`
   * values — see harness-step-agent.ts. */
  effort?: HarnessEffort;
  /** Spending cap to pass to the agent's CLI, in that agent's own unit —
   * see harness-step-agent.ts's `HarnessStepBudget`. Only meaningful for
   * an agent whose `HARNESS_AGENT_CAPABILITIES` entry declares a
   * `budgetField`. */
  budget?: HarnessStepBudget;
  /** Which chain stage this command is running, when it is part of one.
   * Set by `HarnessChainRunner` beside `model`/`effort`/`budget`, and
   * absent for a single-stage run — which is not a gap but the fact: a
   * `review` a person started by itself belongs to no stage of anything.
   *
   * Recorded on the audit entry, because every stage of a chain runs
   * under the chain's own `runId` (ADR 0012), so nothing else in the
   * record can say which stage spent what. */
  stage?: HarnessStage;
  /** The number of the one task this run was asked to do, when it was
   * asked to do one task rather than a whole change — see
   * `delegated-item-run.ts`. Recorded on the audit entry beside the
   * change, so the log answers "what was this agent asked to do here"
   * without the transcript.
   *
   * Absent for every whole-change run, which is what an absent value
   * has always meant: a run of `implement` covers the change's open
   * work, not one line of it. */
  taskNumber?: string;
  /** Why a `"cancel"` command was issued, where something other than a
   * person asking caused it — a ceiling naming itself.
   *
   * Carried onto the cancelled run's own audit entry. The adapter that
   * emits `cancelled` knows only that its signal aborted, so without this
   * a run cut by a ceiling and a run a person cancelled are
   * indistinguishable in the record. Absent for a person's cancel, which
   * is what an absent reason has always meant.
   *
   * On a `"stop"` command it is the reason the person gave for asking the
   * run to stop, and it is required there: a stop without a reason is
   * refused at the card, and recorded with the chain's ending as
   * `stopRequest` rather than as a cancellation's `reason`. */
  reason?: string;
  /** Only meaningful for a `"resolvePermission"` command: the `requestId`
   * of the `PermissionRequestEvent` being answered (see protocol.ts's
   * `PermissionRequestEvent`). Ignored for every other command kind. */
  permissionRequestId?: string;
  /** Only meaningful for a `"resolvePermission"` command: the answer to
   * give the underlying ACP `session/request_permission` call named by
   * `permissionRequestId`. Ignored for every other command kind. */
  permissionOutcome?: "allow" | "deny";
  /** Only meaningful for an `"answerQuestion"` command: the question
   * answered, as `decisions.md` names it, and the answer. */
  questionId?: string;
  answer?: string;
}

export type EventKind =
  | "started"
  | "stdout"
  | "stderr"
  | "progress"
  | "completed"
  | "failed"
  | "cancelled"
  | "cancelling"
  | "usageReported"
  | "stageStarted"
  | "stageCompleted"
  | "checkpoint"
  | "handedOff"
  /** A structured `session/update` from an ACP-flavored adapter's
   * underlying agent (plan/tool-call/message/diff progress) — see
   * acp-session-driver.ts. Non-terminal, like `stageCompleted`/
   * `checkpoint`: a client that does not recognize it still sees a
   * coherent, if less detailed, event log. */
  | "agentUpdate"
  /** An ACP-flavored adapter's underlying agent asked, via `session/
   * request_permission`, before taking a sensitive action — only emitted
   * by an adapter whose agent genuinely issues that call (see
   * acp-agent-adapters spec.md's "Permission requests are surfaced only
   * where the underlying agent genuinely supports them"). Answered by a
   * `"resolvePermission"` command naming this event's `requestId`.
   * Non-terminal. */
  | "permissionRequest"
  /** A `permissionRequest` is no longer pending: it was answered - from
   * whichever surface - or the agent withdrew it. Non-terminal. */
  | "permissionSettled"
  /** A `"stop"` command reached the run — see `StopRequestedEvent`.
   * Non-terminal. */
  | "stopRequested"
  /** An agent put a question to the operator (ADR 0042). Non-terminal. */
  | "question"
  /** The run stopped to wait for the answers to its open questions.
   * Non-terminal. */
  | "awaitingAnswers"
  /** A question of the run was answered. Non-terminal. */
  | "questionAnswered";

interface BaseEvent {
  runId: string;
  /** ISO 8601 timestamp. */
  timestamp: string;
}

export interface StartedEvent extends BaseEvent {
  kind: "started";
  command: CommandKind;
  cwd: string;
}

export interface StdoutEvent extends BaseEvent {
  kind: "stdout";
  chunk: string;
}

export interface StderrEvent extends BaseEvent {
  kind: "stderr";
  chunk: string;
}

export interface ProgressEvent extends BaseEvent {
  kind: "progress";
  /** Arbitrary human-readable progress message (not necessarily numeric —
   * specific agents report progress differently). */
  message: string;
}

export interface CompletedEvent extends BaseEvent {
  kind: "completed";
  /** Resulting diff/changes, if applicable (best-effort, may be empty). */
  summary?: string;
  /** What a review run said of the plan, read from its closing
   * `Review verdict:` line; absent on every other run and on a review that
   * printed none (ADR 0041). */
  reviewVerdict?: "ready" | "changes-needed";
}

export interface FailedEvent extends BaseEvent {
  kind: "failed";
  reason: string;
  /** What is known about why, from the reason and the end of the run's
   * output (the-supervisor-advises). Optional: every failure written
   * before it existed reads as it did, and a reader that ignores it reads
   * on. */
  diagnosis?: FailureDiagnosis;
}

/** The run ended because it was cancelled. Emitted only once the process
 * is gone — see `cancelling` below, and
 * openspec/changes/cancel-reports-what-happened/. */
export interface CancelledEvent extends BaseEvent {
  kind: "cancelled";
  /** Why the run was cancelled, where something other than a person
   * asking caused it — a time ceiling naming itself and its value, for
   * instance.
   *
   * Optional on purpose: every cancellation written before this field
   * existed means "a person asked", and an absent reason has to keep
   * meaning exactly that. A reader seeing a cancellation otherwise
   * cannot tell a click from a rule firing. */
  reason?: string;
}

/** Cancellation was asked for and has not taken effect yet.
 *
 * **Not terminal.** A run in this state is still running, and everything
 * that follows from a run being active still follows — most importantly,
 * the control that cancels it stays available. That is the whole reason
 * this kind exists: `cancelled` used to be emitted the instant the
 * request arrived, so a surface that treats terminal events as
 * end-of-run withdrew the user's only lever while the agent carried on
 * working (reported 2026-09-03 against `copilot-cli-acp`).
 *
 * A consumer that does not know this kind degrades to the behaviour it
 * had before it existed, because ignoring a non-terminal event changes
 * nothing. `attempted` says what was actually tried, so a surface can
 * tell "nothing was running" from "we asked the process to stop". */
/** What the agent reported spending on this run so far.
 *
 * **Not terminal.** Usage arrives while a run is working — ACP's
 * `usage_update` notifications during the turn, and its
 * `PromptResponse.usage` at the end — so this is an observation, not an
 * outcome. A consumer that ignores it behaves exactly as before it
 * existed.
 *
 * Carries only what the agent said. Nothing here is estimated, derived
 * from a price table, or converted between currencies — see
 * `AgentUsage`, and ADR 0017 decision 5. An agent that reports nothing
 * produces no event at all, which is different from reporting zero. */
export interface UsageReportedEvent extends BaseEvent {
  kind: "usageReported";
  usage: AgentUsage;
}

export interface CancellingEvent extends BaseEvent {
  kind: "cancelling";
  attempted: "termination-requested" | "nothing-to-cancel";
}

/** A chain stage is about to begin. Emitted once per stage that actually
 * runs, immediately before it starts — after any check that could refuse
 * it, so a stage refused at a budget ceiling is never announced as having
 * started.
 *
 * Exists because a chain publishes every stage under one `runId` and
 * otherwise names a stage only when it *ends* (`stageCompleted`/
 * `checkpoint`). Without this, a surface cannot attribute anything to the
 * FIRST stage (no boundary precedes it) or to the stage a chain stopped
 * during (no boundary follows it) — which is precisely the stage that
 * spent the money. Non-terminal and carries no decision: a consumer that
 * ignores it behaves exactly as before it existed.
 *
 * `agentId` is `""` for a stage that runs no agent (`archive`, `git`),
 * the same convention `CheckpointEvent.nextAgentId` already uses — it
 * reads as "no agent required", not "unknown". */
export interface StageStartedEvent extends BaseEvent {
  kind: "stageStarted";
  /** `ChainPart`, not `HarnessStage`: a declared step (ADR 0021) travels
   * this same timeline rather than a second pair of events, so a surface
   * that renders a chain renders one without knowing what it is. */
  stage: ChainPart;
  agentId: string;
  /** Which attempt at this stage is starting, counting from one. Absent
   * on a first attempt — the case every chain had before stages could be
   * attempted again, and the case a surface should render exactly as it
   * always did. */
  attempt?: number;
  /** Why the previous attempt ended, present only alongside `attempt`.
   * Without it a reader sees the same stage announced twice and cannot
   * tell a retry from a duplicate. */
  previousAttemptReason?: string;
  /** Present on the review stage's second start, where its review asked for
   * changes and the plan is being updated before apply: the review stage
   * runs `update` (ADR 0041). Absent on every other start. */
  updating?: true;
}

/** A chain stage finished and the next one is starting immediately (no
 * confirmation required for this transition). */
export interface StageCompletedEvent extends BaseEvent {
  kind: "stageCompleted";
  stage: ChainPart;
  nextStage: ChainPart;
}

/** A chain paused between stages, waiting for a `"confirmCheckpoint"` (or
 * `"cancel"`) command before it proceeds to `nextStage`. */
export interface CheckpointEvent extends BaseEvent {
  kind: "checkpoint";
  stage: ChainPart;
  nextStage: ChainPart;
  nextAgentId: string;
}

/** A stage was handed to the host's own chat instead of being spawned
 * and observed — see docs/adr/0016-harness-stage-dispatch-via-vscode-
 * chat.md. Non-terminal: nothing observes the chat session's work, so no
 * `completed`/`failed`/`cancelled` follows it for that stage. */
export interface HandedOffEvent extends BaseEvent {
  kind: "handedOff";
  stage: HarnessStage;
}

/** A structured `session/update` from an ACP-flavored adapter's
 * underlying agent — see `EventKind`'s `"agentUpdate"` member and
 * acp-session-driver.ts. `update` carries the ACP peer's own
 * `SessionUpdate` payload (a `sessionUpdate` discriminant plus a
 * variant-specific shape — `agent_message_chunk`/`tool_call`/
 * `tool_call_update`/`plan`/... per the ACP schema) opaque to this
 * protocol layer, exactly as `stdout`'s `chunk` is opaque text for the
 * raw-text adapters — rendering it is a UI concern, not this layer's. */
export interface AgentUpdateEvent extends BaseEvent {
  kind: "agentUpdate";
  update: Record<string, unknown>;
}

/** An ACP-flavored adapter's underlying agent asked for permission before
 * a sensitive action — see `EventKind`'s `"permissionRequest"` member. */
export interface PermissionRequestEvent extends BaseEvent {
  kind: "permissionRequest";
  /** Names this request for a later `"resolvePermission"` command's
   * `permissionRequestId`. */
  requestId: string;
  /** Human-readable description of the action being requested (from the
   * ACP `session/request_permission` payload's tool-call title). */
  description: string;
}

/** A `permissionRequest` nobody needs to answer any more, said in the run's
 * own stream so every surface showing it stops offering Allow/Deny. Seen
 * live on 2026-10-08: an answer given on the change's card left the run
 * panel's buttons in place, and copilot-cli-acp cancelled a request when a
 * tool call beside it failed and went on, while its buttons stayed. */
export interface PermissionSettledEvent extends BaseEvent {
  kind: "permissionSettled";
  /** The settled request's `requestId`. */
  requestId: string;
  /** Answered with `allow` or `deny`, or `withdrawn` by the agent - it
   * cancelled the request, or its turn ended with it open. */
  outcome: "allow" | "deny" | "withdrawn";
}

/** A `"stop"` command reached the runner.
 *
 * **Not terminal.** With `outcome: "asked"` the run goes on to a sound
 * point — the next task boundary, or the end of its stage — and then ends
 * `cancelled`; until then everything that follows from a run being active
 * still follows. With `outcome: "nothing-to-stop"` the runner had no such
 * run, and nothing follows. `by` is the configured git identity of the
 * host that asked, where it has one — attribution, never authentication.
 * See a-change-is-run-from-its-card. */
export interface StopRequestedEvent extends BaseEvent {
  kind: "stopRequested";
  reason: string;
  by?: string;
  outcome: "asked" | "nothing-to-stop";
}

/** An agent asked the operator something the change's files do not
 * decide, with the `Question for the operator:` marker or, for the built-in
 * local agent, its `ask_operator` tool. Recorded in the change's
 * `decisions.md` as `questionId` (ADR 0042). */
export interface QuestionEvent extends BaseEvent {
  kind: "question";
  questionId: string;
  text: string;
}

/** The run's own work is done but some of its questions are open, so it
 * waits for the answers rather than completing. */
export interface AwaitingAnswersEvent extends BaseEvent {
  kind: "awaitingAnswers";
  questions: Array<{ questionId: string; text: string }>;
}

/** A question was answered, from wherever. */
export interface QuestionAnsweredEvent extends BaseEvent {
  kind: "questionAnswered";
  questionId: string;
  answer: string;
  by?: string;
}

export type Event =
  | StartedEvent
  | StdoutEvent
  | StderrEvent
  | ProgressEvent
  | CompletedEvent
  | FailedEvent
  | CancelledEvent
  | CancellingEvent
  | UsageReportedEvent
  | StageStartedEvent
  | StageCompletedEvent
  | CheckpointEvent
  | HandedOffEvent
  | AgentUpdateEvent
  | PermissionRequestEvent
  | PermissionSettledEvent
  | StopRequestedEvent
  | QuestionEvent
  | AwaitingAnswersEvent
  | QuestionAnsweredEvent;

/** Type guard helper: serializing an Event is just JSON, but we verify
 * that `kind` is one of the known variants when deserializing from an
 * external transport (REST/WS/message bridge), where data arrives as
 * `unknown`. */
export function isEvent(value: unknown): value is Event {
  if (typeof value !== "object" || value === null) return false;
  const v = value as Record<string, unknown>;
  if (typeof v.runId !== "string" || typeof v.timestamp !== "string") return false;
  switch (v.kind) {
    case "started":
      return typeof v.command === "string" && typeof v.cwd === "string";
    case "stdout":
    case "stderr":
      return typeof v.chunk === "string";
    case "progress":
      return typeof v.message === "string";
    case "completed":
      return v.summary === undefined || typeof v.summary === "string";
    case "failed":
      return typeof v.reason === "string";
    case "cancelled":
      return true;
    case "cancelling":
      return v.attempted === "termination-requested" || v.attempted === "nothing-to-cancel";
    case "usageReported":
      return typeof v.usage === "object" && v.usage !== null;
    case "stageStarted":
      return (
        typeof v.stage === "string" && isChainPart(v.stage) && typeof v.agentId === "string"
      );
    case "stageCompleted":
      return (
        typeof v.stage === "string" &&
        isChainPart(v.stage) &&
        typeof v.nextStage === "string" &&
        isChainPart(v.nextStage)
      );
    case "checkpoint":
      return (
        typeof v.stage === "string" &&
        isChainPart(v.stage) &&
        typeof v.nextStage === "string" &&
        isChainPart(v.nextStage) &&
        typeof v.nextAgentId === "string"
      );
    case "handedOff":
      return typeof v.stage === "string" && STAGES.includes(v.stage as HarnessStage);
    case "agentUpdate":
      return typeof v.update === "object" && v.update !== null;
    case "permissionRequest":
      return typeof v.requestId === "string" && typeof v.description === "string";
    case "permissionSettled":
      return typeof v.requestId === "string" && (v.outcome === "allow" || v.outcome === "deny" || v.outcome === "withdrawn");
    case "stopRequested":
      return (
        typeof v.reason === "string" &&
        (v.outcome === "asked" || v.outcome === "nothing-to-stop") &&
        (v.by === undefined || typeof v.by === "string")
      );
    case "question":
      return typeof v.questionId === "string" && typeof v.text === "string";
    case "awaitingAnswers":
      return Array.isArray(v.questions)
        && v.questions.every((question: unknown) =>
          typeof question === "object" && question !== null
          && typeof (question as Record<string, unknown>).questionId === "string"
          && typeof (question as Record<string, unknown>).text === "string");
    case "questionAnswered":
      return typeof v.questionId === "string" && typeof v.answer === "string" && (v.by === undefined || typeof v.by === "string");
    default:
      return false;
  }
}

export function serializeEvent(event: Event): string {
  return JSON.stringify(event);
}

export function deserializeEvent(raw: string): Event {
  const parsed: unknown = JSON.parse(raw);
  if (!isEvent(parsed)) {
    throw new Error(`Failed to deserialize Event: unknown format (${raw})`);
  }
  return parsed;
}
